const ACTIONS = {
  TODO_ADD: 'TODO_ADD',
  TODO_GET_ALL: 'TODO_GET_ALL',
  TODO_REMOVE: 'TODO_REMOVE',
  AUTH_SIGN_IN_REQUEST: '@auth/SIGN_IN_REQUEST',
  AUTH_SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
  AUTH_SIGN_FAILURE: '@auth/SIGN_FAILURE',
  AUTH_SIGN_OUT: '@auth/SIGN_OUT',
  PROFILE_TOGGLE_THEME: '@profile/TOGGLE_THEME',
};

export {ACTIONS};
